import Head from "next/head";
import Image from "next/image";
import CryptoTracker from "./CryptoTracker";

export default function Home() {
  return (
    <div>
      <Head>
        <title>Tradify - Keep track of stocks and crypto at the same place</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
    </div>
  );
}
